version: "3"
services:
  db:
    restart: "always"
    container_name: skinandme-tech-test-db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=my-top-secret-password
      - MYSQL_DATABASE=app
      - MYSQL_USER=dev
      - MYSQL_PASSWORD=dev-password
    volumes:
      - ./db:/var/lib/mysql
    expose:
      - 3306:3306
  app:
    container_name: skinandme-tech-test-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URI=mysql://dev:dev-password@db:3306/app
    volumes:
      - ./src:/src
    ports:
      - "127.0.0.1:9000:9000"
