version: "3"
services:
  app:
    container_name: skinandme-tech-test-app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SQLALCHEMY_DATABASE_URI=sqlite:///app.db
    volumes:
      - ./src:/src
    ports:
      - "127.0.0.1:9000:9000"
